global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "api"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["host.docker.internal:8080"]

  - job_name: "worker"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["host.docker.internal:8081"]

  - job_name: "ml-service"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["ml-service:8000"]

  - job_name: "rabbitmq"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["rabbitmq:15692"]
